project:
  type: book

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Florida Retirement System data"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd # index.qmd must ge in the quarto project root folder
    - qmd/constants.qmd
    - part: "Stand-alone items (only requiring access to frs_constants)"
      chapters:
      - qmd/current_amort_layers.qmd
      - qmd/init_funding_data.qmd
      - qmd/headcount.qmd # get and gross-up the raw headcount data
      - qmd/retiree_distribution.qmd
      - qmd/retirement_rates.qmd
      - qmd/salary.qmd
      - qmd/salary_growth.qmd
    - part: "Data that depend on previously created data"
      chapters:
      - qmd/base_mortality_rates.qmd
      - qmd/mortality_improvement.qmd
      - qmd/termination_rates.qmd
      - qmd/salary_headcount_entrants.qmd # combine 2 previous files, add growth, extract entrants
      - qmd/miscellaneous_info.qmd
    - part: "Assemble list of data for package"
      chapters:
      - qmd/assemble_list.qmd

# bibliography: references.bib

# devtools::load_all("./")

# from pendata folder, in powershell, enter ./runall.bat

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt

editor_options:
  chunk_output_type: console


# additional execution options
  # error: false
  # warning: false
  # message: false  # not sure if allowed
  # note: false  # not sure if allowed

# renv-related commands
# renv::snapshot()
# renv::restore()
# renv::update()
# renv::status()
# Sys.getenv("RENV_PATHS_CELLAR") # RENV_PATHS_SOURCE RENV_PATHS_RENV


# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt

# boyd-mta202324.netlify.app


# possibly use this at start of each doc??
# ---
# output: html_document
# editor_options:
#   chunk_output_type: console
# ---


