# FRS constants

Define constants that will be used throughout the FRS data construction process. Run this before running anything else.


## Setup

```{r}
#| label: setup

source(here::here("data-raw", "libraries.r"))
draw <- here::here("data-raw")

dfrs <- fs::path(draw, "systems", "frs")

frs_constants <- list()

```


## Classes

```{r}
#| label: classes

frs_constants$classes <- c("regular", "special", "admin",
             "eco", "eso", "judges",
             "senior_management")

```


## Grand totals of active members

Used to calibrate headcounts to system totals.

Source:

```{r}
#| label: total_actives

# regular_total_active_member_ <- 537128
# special_total_active_member_ <- 72925
# admin_total_active_member_ <- 104
# eco_eso_judges_total_active_member_ <- 2075
# senior_management_total_active_member_ <- 7610

frs_constants$total_actives <- read_csv("
class, total_actives
regular, 537128
special, 72925
admin, 104
eco_eso_judges, 2075
senior_management, 7610")

```


```{r}
#| label: miscellaneous-constants

# entry_year_range_, entry_age = entrant_profile$entry_age, dist_age = age_range_, yos = yos_range_
# entry_year_range_, entry_age = entrant_profile$entry_age, dist_age = age_range_, yos = yos_range_
# start_year_ <- 2022     #Year of the latest val report (update this when a new val report comes out)
# new_year_ <- 2024       #Year for new entrants with a new tier to join (update this when a new val report comes out)
# min_year_ <- 1970 # No hard rule about this. Should get back to about 40 years from now.
# model_period_ <- 30     #Projection period (typically 30 years)
# entry_year_range_ <- min_year_:(start_year_ + model_period_)

frs_constants <- within(frs_constants,{
  classes <- classes
  start_year <- 2022 # Year of the latest val report (update this when a new val report comes out)
  new_year <- 2024 # Year for new entrants with a new tier to join (update when new val report comes out)
  min_year <- 1970 # why does Reason define min_year as 1970?
  yos_max <- 70
  max_model_period <- 30  # Reason uses 30 but we can override here so that we have a larger possible number
  entry_year_range <- min_year:(start_year + max_model_period)
})

```


## Sort and save in the frs folder

```{r}

# put the list of constants in alpha order by name
frs_constants <- frs_constants[order(names(frs_constants))]

saveRDS(frs_constants, fs::path(dfrs, "frs_constants.rds"))


```

