# Initial funding data

Get initial funding data from `Florida FRS inputs.xlsx`, sheet = "Funding Input".


## Setup

```{r}
#| label: setup
#| output: false

source(here::here("data-raw", "libraries.r"))

draw <- here::here("data-raw")
dfrs <- fs::path(draw, "systems", "frs")
drds <- fs::path(dfrs, "rds")

frs_constants <- readRDS(fs::path(drds, "frs_constants.rds"))

FileName <- "Florida FRS inputs.xlsx"
fullpath <- fs::path(dfrs, FileName)

```


## Get and save initial funding data

For now we simply get the data as-is until we understand better how we use it.

```{r}
#| label: get-and-save-initial-funding-data

init_funding_data <- read_excel(fullpath, sheet = "Funding Input")

saveRDS(init_funding_data, fs::path(drds, "init_funding_data.rds"))

```

## Show initial funding data

Here is the result.

```{r}
#| label: show-initial-funding-data

ifd <- readRDS(fs::path(drds, "init_funding_data.rds"))

# glimpse(ifd)
# names(ifd)
# define variables that will be comma formatted and those that will be percentages
nifd <- names(ifd)
idvars <- c("class", "year")
misc_ratevars <- c("dr_legacy", "dr_new", "roa", "fr_ava", "fr_mva")
ratevars <- c(misc_ratevars, str_subset(nifd, "rate"))
commavars <- setdiff(nifd, c(idvars, ratevars))

ifd |> 
  DT::datatable(
    options = list(scrollX = TRUE, scrollY = TRUE, paging = TRUE, pageLength = 20),
    filter="top") |> 
  formatRound(columns = commavars, digits=0) |> 
  formatPercentage(columns = ratevars, digits=3)

# datatable(ptargets, options = list(scrollX = TRUE, scrollY = '400px', paging = TRUE))
# formatCurrency(columns = c("ptarget"), currency="", digits=0)
# formatPercentage(columns = c("salgrowth"), digits=2)
# formatRound(columns = c("cumprod_increase"), digits=4)


```

## Comparison to the Reason approach

