project:
  type: book
  output-dir: _txtrs  

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false

editor_options:
  chunk_output_type: console

execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Prepare plan data in a consistent format"
  author: "Reason Foundation and Rockefeller College"
  date: today
  date-format: long
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd # index.qmd must be in the quarto project root folder
    # - headcount_salary.qmd
