project:
  type: book
  execute-dir: project  # quarto should look to the project root (pendata)  
  output-dir: _webpage

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false

editor_options:
  chunk_output_type: console

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Prepare plan data in a consistent format"
  author: "Reason Foundation and Rockefeller College"
  date: today
  date-format: long
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd # index.qmd must be in the quarto project root folder
    - amortization_bases.qmd
    - benefit_rules.qmd
    - benefit_rules_test.qmd
    - headcount_salary.qmd
    - salary_growth.qmd
    - withdrawal.qmd
    - assemble_list.qmd


# creating a package
# install.packages(c("devtools", "usethis", "roxygen2", "testthat", "pkgdown"))
# library(devtools)  # Includes usethis
# usethis::create_package("E:/R_projects/Reason/pendata")

# detach(package:pendata)
# remove.packages("pendata")
# devtools::document()
# close any externally open files (e.g., Excel) that are in project folders
#     devtools::build() # not needed when doing devtools::install()
# devtools::install()
# library(pendata)
# plan <- pendata::frs
