project:
  type: book
  execute-dir: project  # quarto should look to the project root (pendata)  
  output-dir: _webpage

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false

editor_options:
  chunk_output_type: console

execute:
  eval: true
  echo: true
  output: false
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "FRS: Prepare plan data in a consistent format"
  author: "Reason Foundation and Rockefeller College"
  date: today
  date-format: long
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Extract Data"
      chapters:
        - get_and_save_extracted_data.qmd
        - test_extracted_data.qmd
    - part: "Amortization Bases"
      chapters:
        - amortization_bases.qmd
        - test_amortization_bases.qmd
        - stage_amortization_bases.qmd
    - part: "Benefit Rules"
      chapters:
        - benefit_rules.qmd
        - benefit_rules_test_cases.qmd
    - part: "Salary & Headcount"
      chapters:
        - headcount_salary.qmd
        - salary_growth.qmd
    - part: "Withdrawals"
      chapters:
        - withdrawal.qmd
    - part: "Assemble list for `pendata` package"
      chapters:
        - assemble_list.qmd

# creating a package
# install.packages(c("devtools", "usethis", "roxygen2", "testthat", "pkgdown"))
# library(devtools)  # Includes usethis
# usethis::create_package("E:/R_projects/Reason/pendata")

# source(here::here("data-raw/R/buildit.R"))

# source(here::here("data-raw", "R", "functions_reset.R"))
# reset_all("frs")
# reset_all("frs", delete=TRUE)

