---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---

# Assemble list

```{r}
#| label: setup

GROOT <- rprojroot::find_root(rprojroot::has_file(".git/index"))
source(fs::path(GROOT, "data-raw", "R", "setup.R"))

```


```{r}
#| label: assemble-list

rds_files <- fs::dir_ls(DIRS$staged, glob = "*.rds")

element_names <- rds_files |>
  path_file() |>
  path_ext_remove()

plan <- rds_files |>
  purrr::map(readRDS) |>
  rlang::set_names(element_names)

plan <- append(list(plan_shortname = PLAN_CONSTANTS$plan), plan)

assign(PLAN_CONSTANTS$plan, plan) # Assign 'plan' to the new name (no intermediate variable)

# devtools::load_all()
# check <- pendata::frs

```


```{r}
#| label: prelim-save-list

save_name <- paste0(PLAN_CONSTANTS$plan, ".rda")
fpath <- fs::path(DIRS$work, save_name)
save(list = PLAN_CONSTANTS$plan, file = fpath, compress = "xz")

# later use this:
# save_name <- paste0(PLAN_CONSTANTS$plan, ".rda")
# fpath <- fs::path(GROOT, "data", save_name)
# save(list = PLAN_CONSTANTS$plan, file = fpath, compress = "xz")

```