---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---    

# Get and save extracted inputs

-   Read all sheets and their metadata
-   Put them into a list
-   Save as .rds in plan working folder

```{r}
#| label: setup
#| output: false

GROOT <- rprojroot::find_root(rprojroot::has_file(".git/index"))
source(fs::path(GROOT, "data-raw", "R", "setup.R"))

```


## Define sheets to get

```{r}
#| label: get-sheetnames

xdpath <- fs::path(DIRS$xddir, PLAN_CONSTANTS$xd_filename)
sheets <- readxl::excel_sheets(xdpath)
sheets_get <- sheets[!stringr::str_starts(sheets, "0_")] |> sort()

```


## Create and save list

Put info into a list, save as rds.

```{r}
#| label: get-save-inputs
#| output: false

a <- proc.time()
inputs_list <- sheets_get |>
  rlang::set_names() |>
  purrr::map(get_data, xdpath)
b <- proc.time()
b - a # 3 secs

names(inputs_list)
inputs_list$benefit_rules

fname <- paste0(PLAN_CONSTANTS$plan, "_inputs_raw.rds")
saveRDS(inputs_list, fs::path(DIRS$work, fname))

```

```{r}
#| label: check-inputs
#| eval: false

fname <- paste0(PLAN_CONSTANTS$plan, "_inputs_raw.rds")
check <- readRDS(fs::path(DIRS$work, fname))

names(check)

```


```{r}
#| label: stop
#| echo: false

knitr::knit_exit()
```

