---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---    

# Tests: Constants

```{r}
#| label: setup

GROOT <- rprojroot::find_root(rprojroot::has_file(".git/index"))
source(fs::path(GROOT, "data-raw", "R", "setup.R"))

```

```{r}

constants <- readRDS(fs::path(DIRS$work, "constants_assumptions.rds"))

```


```{r}
#| label: tests
#| echo: true

print("no tests yet for constants_assumptions")
test_results <- TRUE

# # here::here("data-raw/plans/tests/testthat/test_headcount_salary.R"),

# test_results <- test_that("sum of amortization bases", {
#   amosum <- sum(amortization_bases$amo_balance)
#   expect_gte(amosum, 0)
# }) # returns a boolean; test_file returns a list

```


```{r}

fpath <- fs::path(DIRS$work, "tests_constants_assumptions.csv")

if (fs::file_exists(fpath)) {
  fs::file_delete(fpath)
}

tibble(
  test = "all constants_assumptions tests passed",
  passed = test_results # all_tests_passed(test_results)
) |>
  readr::write_csv(fpath)

```