---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---    

# Tests: Extracted data

```{r}
#| label: setup

GROOT <- rprojroot::find_root(rprojroot::has_file(".git/index"))
source(fs::path(GROOT, "data-raw", "R", "setup.R"))

```


```{r}
#| eval: true

fname <- paste0(PLAN_CONSTANTS$plan, "_inputs_raw.rds")
input_data_list <- readRDS(fs::path(DIRS$work, fname))

```


## Test whether necessary sheets are included

```{r}
#| label: sheets-tests

# here::here("data-raw/plans/tests/testthat/test_headcount_salary.R"),

test_results <- testthat::test_file(
  # here::here("data-raw/plans/tests/testthat/test_extracted_sheets.R"),
  fs::path(GROOT, "data-raw/plans/tests/testthat/test_extracted_sheets.R"),
  reporter = testthat::TapReporter$new()
)

```


```{r}

fpath <- fs::path(DIRS$work, "tests_extracted_data.csv")

if (fs::file_exists(fpath)) {
  fs::file_delete(fpath)
}

tibble(
  test = "all data extraction tests passed",
  passed = all_tests_passed(test_results)
) |>
  readr::write_csv(fpath)

```