---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    css: wider.css
---

# Headcount and salary tables

```{r}
#| label: setup

source(here::here("R", "folders.R"))
source(here::here("R", "libraries.R"))

# get raw extracted data as a list
plan <- "frs"
plandir <- fs::path(DPLANS, plan)
xddir <- fs::path(plandir, "extracted_data")

rawdata <- readRDS(fs::path(xddir, "frs_inputs_raw.rds"))
names(rawdata)

```

```{r}
#| label: data-for-experimentation

sheet <- "headcount_admin"
info <- rawdata[[sheet]]$info
data <- rawdata[[sheet]]$data

```

```{r}
#| label: function-flip

flip <- function(
  data, # data frame to be flipped
  rowvar, # name to use as prefix for row identifiers -- string -- e.g., "age"
  colvar, # name to use as prefix for column identifiers -- string -- e.g., "yos"
  rowlb = NULL, # lower bounds for the row -- numeric vector -- e.g., 10 if the row label is "10-19"
  rowub = NULL, # upper bounds for the row -- numeric vector
  rowlabels = NULL, # string vector, if missing will use 1st column
  collb = NULL, # lower bounds for the columns in the raw data -- numeric vector -- e.g., 20 if column label is "20-24"
  colub = NULL, # upper bounds for the column -- numeric vector
  collabels = NULL # if NULL will use column names
) {
  # flip assumes a data frame where first column is a label and other columns are (or will be converted to) numeric
  if (is.null(rowlabels)) {
    rowlabels <- data |> pull(1)
  }
  if (is.null(collabels)) {
    collabels <- names(data)[-1]
  }
  coltbl <- tibble(collabel = collabels, collb, colub)

  datalong <- data |>
    select(-1) |>
    mutate(rowlabel = rowlabels, rowlb = rowlb, rowub = rowub) |>
    pivot_longer(
      cols = -c(rowlabel, rowlb, rowub),
      names_to = "collabel"
    ) |>
    left_join(coltbl, by = join_by(collabel)) |>
    relocate(value, .after = colub) |>
    mutate(value = replace_na(as.numeric(value), 0)) |>
    rename_with(
      .fn = \(x) str_replace(x, "row", paste0(rowvar, "_")),
      .cols = starts_with("row")
    ) |>
    rename_with(
      .fn = \(x) str_replace(x, "col", paste0(colvar, "_")),
      .cols = starts_with("col")
    )
  return(datalong)
}

# flip(
#   data,
#   rowvar = "age",
#   colvar = "yos",
#   rowlb = agelb,
#   rowub = ageub,
#   collb = yoslb,
#   colub = yosub
# )

```

## Define sheets, labels, bounds and other flip arguments for headcount and salary

```{r}
#| label: define-sheets

# make sure sheet names look right

(hcsheets <- stringr::str_subset(names(rawdata), "headcount_"))
(salsheets <- stringr::str_subset(names(rawdata), "salary_"))


```

```{r}
#| label: define-arguments

# the following arguments pertain both to headcount and salary

agemax <- 110
yosmax <- 70

rowvar <- "age"
colvar <- "yos"

agelb <- c(0, seq(20, 65, 5), 0)
ageub <- c(20, seq(24, 64, 5), agemax, agemax)

yoslb <- c(0, seq(5, 50, 5), 0)
yosub <- c(seq(4, 49, 5), yosmax, yosmax)

# make sure these look right
cbind(agelb, ageub)
cbind(yoslb, yosub)

```

## Get headcount and salary sheets and create a long tibble

```{r}
#| label: create-long-hcs-tibble

sheet_names <- c(hcsheets, salsheets)

data_list <- sheet_names |>
  map(\(x) pluck(rawdata, x, "data")) |>
  setNames(sheet_names)

names(data_list)

tbl_list <- purrr::map(
  data_list,
  flip,
  rowvar = rowvar,
  colvar = colvar,
  rowlb = agelb,
  rowub = ageub,
  collb = yoslb,
  colub = yosub
)

hcs_tbl <- list_rbind(tbl_list, names_to = "src") |>
  separate(src, into = c("variable", "class"), sep = "_", extra = "merge") |>
  mutate(
    rectype = case_when(
      age_label == "Total Count" ~ "total",
      yos_label == "All Years" ~ "total",
      .default = "detail"
    )
  )

```

```{r}
#| label: inspect-hcs-tbl

glimpse(hcs_tbl)
summary(hcs_tbl) # no missing values
skimr::skim_without_charts(hcs_tbl)
skimr::skim(hcs_tbl)
count(hcs_tbl, age_lb, age_ub, age_label)
count(hcs_tbl, yos_lb, yos_ub, yos_label) # note that yos max is 1 less than what the label shows
count(hcs_tbl, variable, class)
count(hcs_tbl, variable, rectype)

```

## Tests

For now, put tests inline. Later move or add them to package tests.

```{r}
#| label: headcount-salary-tests

testthat::local_edition(3)
library(testthat)
withr::deferred_clear()

hcsums <- hcs_tbl |>
  filter(
    variable == "headcount",
    class == "regular"
  ) |>
  summarise(value = sum(value), .by = c(class, age_label, rectype)) |>
  pivot_wider(names_from = rectype)

test_that("headcount detail sums equal headcount totals, all age groups", {
  hcsums <- hcs_tbl |>
    filter(
      variable == "headcount",
      age_label != "Total Count"
    ) |>
    summarise(value = sum(value), .by = c(class, age_label, rectype)) |>
    pivot_wider(names_from = rectype)

  expect_equal(hcsums$detail, hcsums$total, tolerance = 1e-8)
})

test_that("headcount detail sums equal headcount totals, all yos groups", {
  hcsums <- hcs_tbl |>
    filter(
      variable == "headcount",
      yos_label != "All Years"
    ) |>
    summarise(value = sum(value), .by = c(class, yos_label, rectype)) |>
    pivot_wider(names_from = rectype)

  expect_equal(hcsums$detail, hcsums$total, tolerance = 1e-8)
})

test_that("headcount detail sums equal headcount totals, grand total", {
  hcsums <- hcs_tbl |>
    filter(
      variable == "headcount",
      rectype == "detail" |
        (age_label == "Total Count" & yos_label == "All Years")
    ) |>
    summarise(value = sum(value), .by = c(class, rectype)) |>
    pivot_wider(names_from = rectype)

  expect_equal(hcsums$detail, hcsums$total, tolerance = 1e-8)
})


test_that("calculated column salary totals (age groups) equal reported", {
  reported <- hcs_tbl |>
    filter(
      variable == "salary",
      rectype == "total",
      yos_label == "All Years"
    ) |>
    select(class, age_label, value)

  calculated <- hcs_tbl |>
    filter(yos_label != "All Years") |> # rectype == "detail", yos_label != "All Years"
    select(variable, class, yos_label, age_label, value) |>
    pivot_wider(names_from = variable) |>
    mutate(payroll = headcount * salary) |>
    summarise(
      headcount = sum(headcount),
      payroll = sum(payroll),
      .by = c(class, age_label)
    ) |>
    mutate(salary = replace_na(payroll / headcount, 0))

  compare <- left_join(
    reported |>
      select(class, age_label, reported = value),
    calculated |>
      select(class, age_label, calculated = salary),
    by = join_by(class, age_label)
  ) |>
    arrange(desc(abs(calculated - reported)))

  # expect_equal(compare$calculated, compare$reported, tolerance = 1e-8)
  expect_true(all(abs(compare$calculated - compare$reported) < 1)) # relaxed test
})

test_that("calculated row salary totals (yos groups) equal reported", {
  reported <- hcs_tbl |>
    filter(
      variable == "salary",
      rectype == "total",
      age_label == "Total Count"
    ) |>
    select(class, yos_label, value)

  calculated <- hcs_tbl |>
    filter(age_label != "Total Count") |>
    select(variable, class, yos_label, age_label, value) |>
    pivot_wider(names_from = variable) |>
    mutate(payroll = headcount * salary) |>
    summarise(
      headcount = sum(headcount),
      payroll = sum(payroll),
      .by = c(class, yos_label)
    ) |>
    mutate(salary = replace_na(payroll / headcount, 0))

  compare <- left_join(
    reported |>
      select(class, yos_label, reported = value),
    calculated |>
      select(class, yos_label, calculated = salary),
    by = join_by(class, yos_label)
  ) |>
    arrange(desc(abs(calculated - reported)))

  # expect_equal(compare$calculated, compare$reported, tolerance = 1e-8)
  expect_true(all(abs(compare$calculated - compare$reported) < 1)) # relaxed test
})


test_that("calculated grand total salary equals reported grand total salary", {
  # NOTE: This will be important if we construct additional details for age groups or yos groups
  reported <- hcs_tbl |>
    filter(
      variable == "salary",
      rectype == "total",
      age_label == "Total Count",
      yos_label == "All Years"
    ) |>
    select(class, reported = value)

  calculated <- hcs_tbl |>
    filter(rectype == "detail") |>
    pivot_wider(names_from = variable) |>
    mutate(payroll = headcount * salary) |>
    summarise(
      headcount = sum(headcount),
      payroll = sum(payroll),
      .by = c(class, rectype)
    ) |>
    mutate(
      salary = replace_na(payroll / headcount, 0)
    ) |>
    select(class, calculated = salary)

  compare <- left_join(
    reported |>
      select(class, reported),
    calculated |>
      select(class, calculated),
    by = join_by(class)
  ) |>
    arrange(desc(abs(calculated - reported)))

  # expect_equal(compare$calculated, compare$reported, tolerance = 1e-8)
  expect_true(all(abs(compare$calculated - compare$reported) < 1)) # relaxed test
})

```

## If tests pass, drop totals, do final cleanup, and save details for later inclusion in package

```{r}

```